stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

build-linux:
  extends: .build
  tags:
    - linux

build-windows:
  extends: .build
  tags:
    - windows
